### ISSUE TITLE
Create a Code verification page 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/CollegeReboot#47]
Use Route name

 " /emailreset "

This pics shown as a reference or sample

![Screenshot_3](https://user-images.githubusercontent.com/31253617/210840214-34fb0d71-c513-463d-a101-ca93996a2388.png)

**Comment by rohinish404** [comment]
Can i work on this issue?

**Comment by rohinish404** [comment]
Actually i tried setting up the project locally but its giving some errors. Do u have any guide for setting it up locally.

**Comment by rohinish404** [comment]
Actually i was running it with npm start i'll give npm run start a try.

**Comment by rohinish404** [comment]
<img width="1440" alt="Screenshot 2023-01-08 at 11 52 35 PM" src="https://user-images.githubusercontent.com/92542124/211212447-c1e9e932-f049-4f9b-ae7f-fb73aa721bf6.png">
I tried running it using the cmnds and it ran successfully but now im getting this error. I tried looking for the error solution but not sure what to do next. Because of this error the homepage is not displaying.

**Comment by Ayushpanditmoto** [comment]
@rohinish404 yes i am aware of this issue ,after user login and signup whole screen goes white

**Comment by rohinish404** [comment]
So how should i proceed with this. If i cannot see the new page i made in my loaclhost i cannot build it. Also can i create an issue and pr regarding the process of running the project on the localhost. Its not clearly mentioned in the readme.

**Comment by Ayushpanditmoto** [comment]
i have fixed this issue you can now 1stly clear your cookies data then try again

**Comment by rohinish404** [comment]
<img width="1440" alt="Screenshot 2023-01-10 at 12 49 40 PM" src="https://user-images.githubusercontent.com/92542124/211486693-54de11ac-8e7e-4dea-81a8-6ffdf597b49f.png">
How does this look? should i make a pr? any other changes you would like?
